--CREACION TABLAS
CREATE TABLE AUTHOR(
	ID NUMBER(10) not null,
	NAME VARCHAR2(40),
	BIRTHDATE VARCHAR2(20),
	CONSTRAINT idauthor_pk
	PRIMARY KEY (id)
)
CREATE TABLE LIBRARY(
	ID NUMBER(10) not null,
	NAME VARCHAR2(40),
	ADDRESS VARCHAR2(50),
	CONSTRAINT idlibrary_pk
	PRIMARY KEY (id)
)
CREATE TABLE PUBLISHER(
	ID NUMBER(10)not null,
	NAME VARCHAR2(40),
	nit number(20),
	CONSTRAINT idpublisher_pk
	PRIMARY KEY (id)
)
CREATE TABLE BOOK(
	ID NUMBER(38) null,
	ISBN NUMBER (38),
	author VARCHAR2 (100),
	published VARCHAR2 (100),
	lan VARCHAR2 (100),
	publisher VARCHAR2 (100),
	CONSTRAINT idbook_pk
	PRIMARY KEY (id)
)
--CREACION CONSTRAINTS
ALTER TABLE book
ADD CONSTRAINT authorid_fk FOREIGN KEY (authorid)
REFERENCES author (id);

ALTER TABLE book
ADD CONSTRAINT libraryid_fk FOREIGN KEY (libraryid)
REFERENCES library (id);

ALTER TABLE book
ADD CONSTRAINT publisherid_fk FOREIGN KEY (publisherid)
REFERENCES publisher (id);
--CREACION SECUENCIAS
CREATE SEQUENCE author_sq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;
CREATE SEQUENCE library_sq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;
CREATE SEQUENCE publisher_sq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;
CREATE SEQUENCE book_sq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;
CREATE TABLE ENDAVA_LIBRARY(
	E_ID NUMBER(37) NOT NULL,
	name VARCHAR2 (100),
	E_ISBN NUMBER (37),
	E_author VARCHAR2 (100),
	E_published VARCHAR2 (100),
	E_lan VARCHAR2 (100),
	E_publisher VARCHAR2 (100)
);

